# Generated by Django 3.0.6 on 2020-05-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lesson',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.Lesson'),
        ),
    ]
