# Generated by Django 3.0.6 on 2020-05-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time', models.DateTimeField()),
                ('level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=1, verbose_name='Level')),
                ('language', models.ManyToManyField(to='main_app.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='level',
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='student',
            field=models.ManyToManyField(null=True, to='main_app.Student'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='student',
            name='lesson',
            field=models.ManyToManyField(to='main_app.Lesson'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Language'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lesson',
            field=models.ManyToManyField(null=True, to='main_app.Lesson'),
        ),
    ]
